services:
  redis:
    image: redis:8.0-alpine
    container_name: document-processor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

volumes:
  redis-data:
